# Project 2 Phase 1: Team Cloud Computing
------

**Basic Information**

Liliana Giraud,
03105688,
Due Date April 7, 2026

# Task 1: Dataset Information

**What is the title or topic of the date set?**

The topic/title of our dataset is job salary predictions. The dataset takes in information from several sources to measure the education level, 
experience level, certifications, to name a few.

**What is the source from which the dataset was obtained?**

The dataset was sourced from *Kaggle* dataset access.

**Purpose of the dataset?**

The purpose of this dataset is to summarize and predict job placements by collecting data across multiple occupations to see common trends in job
employment.

# Task 2: Basic Data Exploration

**Loading Dataset**

In [42]:
import pandas as pd
job_df = pd.read_csv("./job_salary_prediction_dataset.csv")

In [43]:
job_df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [44]:
job_df.tail()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [45]:
job_df.shape

(250000, 10)

In [46]:
job_df.columns

Index(['job_title', 'experience_years', 'education_level', 'skills_count',
       'industry', 'company_size', 'location', 'remote_work', 'certifications',
       'salary'],
      dtype='object')

# Task 3: Data types and structures

In [48]:
job_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

**Identify numerical vs categorial columns**

Our dataset uses both numerical and categorical data to predict job placement. 
Numerical EX: Experience level, skills count, certifications, salary. 
Categorial EX: job title, education level, industry, company size, location, remote work.

**Are there any data types that should be converted?**

No, our group believes that our variables are represented the effiently the way that they are. Many of the numerical columns need to be represented
by numbers. Additionally, the categorial data is best represented by titles/words instead of numbers.

# Task 4: Descriptive summary

In [53]:
job_df.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [54]:
job_df.describe(include='all')

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
count,250000,250000.000000,250000,250000.000000,250000,250000,250000,250000,250000.000000,250000.000000
unique,12,NaN,5,NaN,10,5,10,3,NaN,NaN
top,Backend Developer,NaN,Master,NaN,Finance,Large,Australia,No,NaN,NaN
freq,21125,NaN,50352,NaN,25393,50254,25258,83621,NaN,NaN
mean,NaN,10.005408,NaN,9.997812,NaN,NaN,NaN,NaN,2.491928,145718.080524
std,NaN,6.060602,NaN,5.479288,NaN,NaN,NaN,NaN,1.706475,37407.952729
min,NaN,0.000000,NaN,1.000000,NaN,NaN,NaN,NaN,0.000000,31867.000000
25%,NaN,5.000000,NaN,5.000000,NaN,NaN,NaN,NaN,1.000000,119358.000000
50%,NaN,10.000000,NaN,10.000000,NaN,NaN,NaN,NaN,2.000000,143453.000000
75%,NaN,15.000000,NaN,15.000000,NaN,NaN,NaN,NaN,4.000000,169492.000000
max,NaN,20.000000,NaN,19.000000,NaN,NaN,NaN,NaN,5.000000,333046.000000

**Summary Interpretation**

---

**What do these statistics tell you about numerical columns?/ Is there anything inconsistent or unusual?**

No, our group has determined that this datapoints show that many of the top-paid individuals in the job market are those with the most certifications, 
experience in the field, and skill count. As seen by the 25%, 50%, and 75% columns, the salary of these individuals is directly influenced by their 
experience, skill count, and  certifications. There are no outstanding outlays skewing the data, which makes this dataset consistent. There are no 
points where this dataset is unusual or inconsistent.

# Task 5: Missing or duplicated data

In [58]:
job_df.isnull().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [59]:
job_df.duplicated().sum()

0

**There is no duplicated or missing values throughout the dataset as seen by the information provided above**

# Project 2 Phase 2

##### Edric Bussie #004001173

### TASK 06 :: ADD A NEW COLUMN

In [4]:
import pandas as pd

job_df = pd.read_csv('job_salary_prediction_dataset.csv')

In [5]:
job_df['salary_per_skill'] = job_df['salary'] / job_df['skills_count']

In [6]:
job_df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,salary_per_skill
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,54706.500000
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,5515.529412
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,37030.750000
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,14547.923077
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,23581.285714

##### The salary_per_skill column represents the average amount of salary associated with each skill required for a given job. It is calculated by dividing the total salary by the number of skills listed for that position, giving a rough estimate of how much each individual skill contributes to overall pay.

### TASK 07 :: FILTER THE DATA

In [8]:
high_paid_remote = job_df[(job_df['salary'] > 100000) & (job_df['remote_work'] == 1)]
high_paid_remote.head()

Empty DataFrame
Columns: [job_title, experience_years, education_level, skills_count, industry, company_size, location, remote_work, certifications, salary, salary_per_skill]
Index: []

In [9]:
experienced_grads = job_df[(job_df['experience_years'] >= 5) & (job_df['education_level'] == 'Bachelor')]
experienced_grads.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,salary_per_skill
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,54706.500000
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,5515.529412
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,23581.285714
17,DevOps Engineer,10,Bachelor,1,Education,Large,UK,No,2,155931,155931.000000
22,DevOps Engineer,10,Bachelor,8,Government,Small,Germany,Yes,1,151828,18978.500000

##### Two subsets were created to isolate meaningful patterns within the dataset based on salary, work style, experience, and education.

The first subset high_paid_remote includes jobs that offer salaries above $100,000 and are classified as remote positions. This subset is interesting because it highlights high-paying opportunities that also provide flexibility in scheduling.

The second subset experienced_grads focuses on jobs that require at least five years of experience and a Bachelor’s degree. This subset is useful for understanding mid- to senior-level positions and the typical expectations tied to them. It allows you to explore how experience and education together influence job qualifications and salary potential.

Together, these subsets are interesting because they narrow down the dataset into targeted groups, making it easier to identify patterns in them and draw conclusions about high-value jobs.

### TASK 08 :: UNIQUE VALUES & CATEGORIES

In [12]:
job_df['job_title'].unique()
job_df['education_level'].unique()
job_df['industry'].unique()
job_df['company_size'].unique()
job_df['location'].unique()
job_df['remote_work'].unique()

array(['Hybrid', 'No', 'Yes'], dtype=object)

In [16]:
# The most useful categorical columns for grouping and insights are:
job_df['job_title'].value_counts()
job_df['education_level'].value_counts()
job_df['industry'].value_counts()
job_df['company_size'].value_counts()
job_df['location'].value_counts()
job_df['remote_work'].value_counts()

remote_work
No        45978
Hybrid    45936
Yes       45763
Name: count, dtype: int64

# Phase 3: Mission Brief